[package]
name = "elvi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_error = "1.9.2"
pest = "2.7.10"
pest_consume = { git = "https://github.com/Nadrieril/pest_consume.git" }
pest_derive = { version = "2.7.10", features = ["grammar-extras"] }
snailquote = "0.3.1"
