// Main rules
/// A for loop.
forLoop = { "for" ~ space+ ~ #variable = elviWord ~ (space+ ~ "in" ~ space+ ~ (#loop_match = forLoopMatch ~ (space+ ~ #loop_match = forLoopMatch)*))? ~ newline+ ~ (space+)? ~ "do" ~ (space+ | newline+) ~ (#inner_for = statement)+ ~ newline+ ~ (space+)? ~ "done" }

/// Whatever can match the iterations on a for loop.
forLoopMatch = ${
    backtickSubstitution // We do the + here so we can differentiate between "${foo}"/* and "${foo}" /*

  | elviWord+
}
