// Main rules
singleQuoteString = @{ "'" ~ singleInner ~ "'" }
doubleQuoteString = @{ "\"" ~ doubleInner ~ "\"" }

// A wrapper so people don't have to { singleQuoteString | doubleQuoteString }
anyString = ${ singleQuoteString | doubleQuoteString }

// Helper rules
doubleInner = @{ (!("\"" | "\\") ~ ANY)* ~ (escape ~ doubleInner)? }
singleInner = @{ (!("'") ~ ANY)* }
escape      = @{ "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "n" | "r" | "t") }
